acm-ucr/r-mate

src/components/Profile.jsx
=> Profile Page

src/screens/loading.js
=> Loading Page

src/components/Bug.jsx
=> Bug Screen

src/components/ResourcesCard.jsx
=> create resources card

src/components/Feedback.jsx, tailwind.config.js
=> Added Feedback page

src/components/BottomBar.jsx
=> Add icons to BottomBar component

src/components/Feedback.jsx
=> Changed from style sheet to tailwind utility class

src/components/RCard.jsx
=> Digital R'Card template with rounded border corners

src/components/Feedback.jsx
=> Adjusted feedback component sizes

src/components/Account.jsx
=> Converted to Nativewind Account Display

src/components/BottomBar.jsx
Made bottom nav bar wider and removed roundness as it didn't work nicely with the positioning. If roundness is desired, I can open a new PR and work on integrating it smoothly.
=> Bottom nav bar wider

src/components/SRCEventsCard.jsx
=> SRC Events Card

package-lock.json, package.json, src/components/SRCCountCard.jsx
=> Add SRCCountCard

src/components/CallButton.jsx
=> Call Button

src/components/TopBar.jsx
=> Remove unused TouchableOpacity from component

src/components/Bug.jsx, src/components/Feedback.jsx
should work on both bug and feedback page. Simulator using Xcode might not show keyboard sometime, but it works fine when testing on iPhone
=> Hide keyboard when touching blank area

src/components/BackButton.jsx
=> Created back button

src/components/RadioButton.jsx, src/components/RadioQuestion.jsx
Updated font size and style
Updated spacing and format
Updated color scheme
=> Added styling to radio question/button

src/components/ParkingLotFilter.jsx
Repurposed https://github.com/acm-ucr/R-Mate/pull/108 because the Figma is identical for both
=> Add parking lot filter

src/components/FoodDetailPage.jsx
- Added **Scrollview** to let the user scroll through options and page if overflow
- TouchOpacity is added to **View on Map** and **Open** button for future implementation purpose
=> Food Detail Page

src/components/Parking.jsx
=> Parking Scrollbar

src/components/FoodDetailPage.jsx
=> Payment options now overflow to the next line

src/components/ParkingLotFilter.jsx
=> All Parking Zones Option

src/components/SurveyCard.jsx, src/components/data/SurveyData.jsx
=> Changed the survey cards to new style

src/components/Dining.jsx
=> Fixed dining back style

src/components/Parking.jsx, src/components/ParkingAvailabilityCard.jsx, src/components/data/ParkingLotTickets.jsx
=> New Parking Items

src/components/Home.jsx, src/navigators/Navigator.jsx, src/screens/loading.js, src/screens/login.js, src/screens/logout.js
Removed all instances of UCR Logo and replaced with editorial message
=> Remove all instances of UCR Logo

src/components/Parking.jsx, src/components/ParkingLotFilter.jsx
=> fixed back button text and dropdown symbol position

src/components/ShortResponseQuestion.jsx, src/components/SurveyForm.jsx, src/components/data/SurveyData.jsx
=> Created a short response survey question

src/components/FoodCard.jsx, src/components/Parking.jsx, src/components/ParkingLotFilter.jsx
=> Fixed the payment methods being cut off and made them go to the next line

src/components/SurveyForm.jsx
=> Added a submit button

src/components/ScaleButton.jsx, src/components/ScaleQuestion.jsx, src/components/SurveyForm.jsx, src/components/data/SurveyData.jsx
=> Created a scale type survey question

src/components/Account.jsx
=> Profile Back Styling

src/components/FoodCard.jsx, src/components/Market.jsx
=> fixed back button text and added 'open' button next to market title
